modified for large file indexes & ARG_MAX

diff --git a/git-filter-orphans b/git-filter-orphans
--- a/git-filter-orphans
+++ b/git-filter-orphans
@@ -1,6 +1,5 @@
 #!/bin/bash
 set -e
-
 GIT_FILTER_ORPHANS_FIND(){
 	##create a list of all blobs
 	echo -e "building indexes\n"
@@ -12,7 +11,7 @@ GIT_FILTER_ORPHANS_FIND(){
 	#build list of all files in index
 	list=`git ls-files | awk '{print "./"$1}'`
 	while read -r file; do
-		uniqueObjectIndex["${file}"]=1
+		uniqueObjectIndex["$file"]=1
 	done <<< "$list"
 
 	#build an index of every sha->file
@@ -20,7 +19,7 @@ GIT_FILTER_ORPHANS_FIND(){
 	while read -r line; do
 		SHA=${line% *}
 		FILE=${line#* }
-		allShasIndex["${SHA}"]="./$FILE"
+		allShasIndex["$SHA"]="./$FILE"
 	done <<< "$allShas"
 
 	#build an index of sha->size
@@ -28,54 +27,101 @@ GIT_FILTER_ORPHANS_FIND(){
 	while read -r line; do
 		SHA=${line% *}
 		SIZE=${line#* }
-		bigObjectIndex["${SHA}"]=$SIZE
+		bigObjectIndex["$SHA"]=$SIZE
 	done <<< "$bigObjects"
 
 	: >$SORT_FILE
 	#sort out any objects they are still in the repo
 	#create a gfo-sorted.txt file
+	count=0
 	for SHA in "${!bigObjectIndex[@]}"; do
-		FILE=${allShasIndex["${SHA}"]}
-		SIZE=${bigObjectIndex["${SHA}"]}
-		if [ -z "${FILE}" ]; then
+		FILE=${allShasIndex["$SHA"]}
+		SIZE=${bigObjectIndex["$SHA"]}
+		if [ -z "$FILE" ]; then
 			continue
 		fi
-		if [[ ! ${uniqueObjectIndex["${FILE}"]} ]]; then
-			uniqueObjectIndex["${FILE}"]=1
-			echo 'storing: ' $FILE
-			echo "${SIZE} ${FILE}" >> "${SORT_FILE}"
+		if [[ ! ${uniqueObjectIndex["$FILE"]} ]]; then
+			count=$((count+1))
+			uniqueObjectIndex["$FILE"]=1
+			echo 'indexed: ' $FILE
+			echo "$SIZE $FILE" >> "$SORT_FILE"
 		fi
 	done;
-	sort -nrk1 "${SORT_FILE}" -o "${SORT_FILE}"
+	sort -nrk1 "$SORT_FILE" -o "$SORT_FILE"
+	echo "$count files indexed in $SORT_FILE"
 }
 
-#eradicate the file or directory from existence
+#eradicate a list of files and directories from existence
 GIT_FILTER_ORPHANS_PURGE(){
 	args=("$@")
 	tmp=""
+	file="${args[0]}"
+	treeFilter="$REPO_ROOT/.gfo.filter.tree"
+	indexFilter="$REPO_ROOT/.gfo.filter.index"
+	: > "$treeFilter"
+	: > "$indexFilter"
+	chmod +x "$treeFilter"
+	chmod +x "$indexFilter"
 	if [ ${#args[@]} -eq 2 ]; then
 		tmp="${args[1]}"
 	fi
-	file="${args[0]}"
-	list=`cat "${file}"`
-	treeFilter=()
-	indexFilter=()
-	count=0
-	while read -r line; do
-		count=$((count+1))
+	cat "$file" | while read line; do
 		file=${line#* }
-		echo $file
-		treeFilter+=("rm -f ${file};")
-		indexFilter+=("git rm -rf --cached --ignore-unmatch ${file};")
-	done <<< "$list"
-	cmd=(git filter-branch --force --prune-empty)
-	if [ ! -z "${tmp}" ]; then
-		cmd+=(-d "${tmp}")
+		echo "rm -f "'"'"$file"'"' >> "$treeFilter"
+		echo "git rm --cached --ignore-unmatch "'"'"$file"'"' >> "$indexFilter"
+	done
+
+   	cmd=(--force --prune-empty)
+	if [ ! -z "$tmp" ]; then
+		cmd+=(-d "$tmp")
 	fi
-	cmd+=(--tree-filter '"'"${treeFilter[@]}"'"')
-	cmd+=(--index-filter '"'"${indexFilter[@]}"'"')
+	cmd+=(--tree-filter "\"$treeFilter\"")
+	cmd+=(--index-filter "\"$indexFilter\"")
 	cmd+=(--tag-name-filter cat -- --all)
-	eval "${cmd[@]}"
+	echo "${cmd[@]}" | xargs git filter-branch
+	rm -f "$treeFilter" "$indexFilter"
+}
+
+#eradicate the file or directory from existence
+GIT_FILTER_ORPHANS_FILTER(){
+	args=("$@")
+	tmp=""
+	file="${args[0]}"
+	if [ ${#args[@]} -eq 2 ]; then
+		tmp="${args[1]}"
+	fi
+   	cmd=(--force --prune-empty)
+	if [ ! -z "$tmp" ]; then
+		cmd+=(-d '"'"$tmp"'"')
+	fi
+	cmd+=(--tree-filter "'rm -f \"$file\"'")
+	cmd+=(--index-filter "'git rm --cached --ignore-unmatch \"$file\"'")
+	cmd+=(--tag-name-filter cat -- --all)
+	echo "${cmd[@]}" | xargs git filter-branch
+}
+
+#recursively removes the directory from existence
+GIT_FILTER_ORPHANS_RMDIR(){
+	args=("$@")
+	tmp=""
+	file="${args[0]}"
+	if [ ${#args[@]} -eq 2 ]; then
+		tmp="${args[1]}"
+	fi
+   	cmd=(--force --prune-empty)
+	if [ ! -z "$tmp" ]; then
+		cmd+=(-d '"'"$tmp"'"')
+	fi
+	#recursive
+	cmd+=(--tree-filter "'rm -rf \"$file\"'")
+	cmd+=(--index-filter "'git rm -rf --cached --ignore-unmatch \"$file\"'")
+	cmd+=(--tag-name-filter cat -- --all)
+	echo "${cmd[@]}" | xargs git filter-branch
+	if [ $? -gt 0 ]; then
+		echo "file: $file not found in tree, recursing..."
+		exit
+	fi
+	echo 'Filter complete!'
 }
 
 #expire old refs and run garbage collection
@@ -93,7 +139,7 @@ GIT_FILTER_ORPHANS_GC(){
 
 #update all refs and tags on remote
 GIT_FILTER_ORPHANS_UPDATE(){
-	echo "Updating repo: ${REPO}"
+	echo "Updating repo: $REPO"
 	git push --force --all
 	git push --force --tags
 }
@@ -102,27 +148,31 @@ GIT_FILTER_ORPHANS_UPDATE(){
 GIT_FILTER_ORPHANS_CLONE(){
 	bak="${REPO}.gfo.bak"
 	tmp=".gfo.tmp"
-	tmpbak="${bak}"
+	tmpbak="$bak"
 	count=1
 	while true; do
-		if [ ! -d "${tmpbak}" ]; then
+		if [ ! -d "$tmpbak" ]; then
 			break
 		fi
 		count=$((count+1))
 		tmpbak="${bak}_${count}"
 	done
-	bak="${tmpbak}"
+	bak="$tmpbak"
 	echo "moving files to backup and cloning..."
-	rm -rf "${tmp}"
-	mkdir "${bak}"
-	mkdir "${tmp}"
+	rm -rf "$tmp"
+	mkdir "$bak"
+	mkdir "$tmp"
 	#move files to backup
-	ls -A | grep -v "^${bak}" | xargs -I file mv file "${bak}"
+	ls -A | grep -v "^$bak" | while read file; do
+		mv "$file" "$bak/"
+	done
 	#clone into current dir
-	git clone file://"${bak}" "${tmp}"
-	ls -A "${tmp}" | xargs -I file mv "${tmp}/"file .
-	rmdir "${tmp}"
-	cp -f "${bak}"/.git/config .git/
+	git clone "file://$bak" "$tmp"
+	ls -A "$tmp" | while read file; do
+		mv "$tmp/$file" .
+	done
+	rmdir "$tmp"
+	cp -f "$bak/.git/config" .git/
 }
 
 #parse arguments and call corresponding methods
@@ -153,22 +203,29 @@ GIT_FILTER_ORPHANS_PARSE(){
 			update)
 				GIT_FILTER_ORPHANS_UPDATE
 				;;
-			filter)
+			rmdir)
 				if [ $argCount -lt 2 ]; then
-					echo 'Error: Must provide a file or directory path with --filter'
+					echo 'Error: Must provide a file or directory path with "rmdir"'
 					exit 0
 				fi
-				GIT_FILTER_ORPHANS_PURGE "${args[1]}" "${tmp}"
+				GIT_FILTER_ORPHANS_RMDIR "${args[1]}" "$tmp"
+				;;
+			filter)
+				if [ $argCount -lt 2 ]; then
+					echo 'Error: Must provide a file or directory path with "filter"'
+					exit 0
+				fi
+				GIT_FILTER_ORPHANS_FILTER "${args[1]}" "$tmp"
 				;;
 			purge) 
 				if [ $argCount -lt 2 ]; then
-					echo 'Error: Must provide a path to a gfo-sorted list file with --purge'
+					echo 'Error: Must provide a path to a gfo-sorted list file with "purge"'
 					exit 0
 				elif [ ! -f "${args[1]}" ]; then
 				   	echo 'Error: No file found matching "'"${args[1]}"'"'
 					exit 0
 				fi
-				GIT_FILTER_ORPHANS_PURGE "${args[1]}" "${tmp}"
+				GIT_FILTER_ORPHANS_PURGE "${args[1]}" "$tmp"
 				;;
 			help)
 				GIT_FILTER_ORPHANS_HELP "${args[@]:1}"
@@ -193,15 +250,15 @@ GIT_FILTER_ORPHANS(){
 	REPO=${REPO#*/}
 	isBare=`git rev-parse --is-bare-repository`
 	#get repo root
-	if [ "${isBare}" == "true" ]; then
+	if [ "$isBare" == "true" ]; then
 		REPO_ROOT=`git rev-parse --git-dir`
-		if [ "${REPO_ROOT}" == "." ]; then
+		if [ "$REPO_ROOT" == "." ]; then
 			REPO_ROOT="$CWD"
 		fi
 	else
 		REPO_ROOT=`git rev-parse --show-toplevel`
 	fi
-	if [ -z "${REPO}" ]; then
+	if [ -z "$REPO" ]; then
 		#bypass error if help command
 		case "${args[0]}" in
 			help)
@@ -214,9 +271,9 @@ GIT_FILTER_ORPHANS(){
 		exit 0
 	fi
 	#chdir to repo root
-	if [ "${REPO_ROOT}" != "${CWD}" ]; then
-		echo "chdir ${CWD} -> ${REPO_ROOT}"
-		cd "${REPO_ROOT}"
+	if [ "$REPO_ROOT" != "$CWD" ]; then
+		echo "chdir $CWD -> $REPO_ROOT"
+		cd "$REPO_ROOT"
 	fi
 	#parse params and call final method
 	GIT_FILTER_ORPHANS_PARSE
@@ -228,13 +285,16 @@ GIT_FILTER_ORPHANS_HELP(){
 	args=("$@")
 	GIT_USER="${args[0]}"
 	CLONE_REPO="${args[1]}"
-	if [ -z "${GIT_USER}" ]; then
+	if [ -z "$GIT_USER" ]; then
 		GIT_USER="<username>"
 	fi
-	if [ -z "${CLONE_REPO}" ]; then
+	if [ -z "$CLONE_REPO" ]; then
 		CLONE_REPO="<clone-repo>"
 	fi
 cat <<-EOL
+
+Git-filter-orphans
+==================
 
 Git-filter-orphans will find all your orphaned objects and
 eradicate them from your git history and repo completely.
@@ -242,15 +302,17 @@ eradicate them from your git history and repo completely.
 
 COMMANDS
 --------
-  find         -find all orphan objects and store them in a list(${SORT_FILE})
+  find         -find all orphan objects and store them in a list($SORT_FILE)
   update       -update your new repo and force push to remote
-  clone        -make a backup of your current repo and clone from it in: ${REPO_ROOT}
+  clone        -make a backup of your current repo and clone from it in: $REPO_ROOT
   gc           -run manual garbage collection on repo (potentially dangerous)
-  filter PATH  -filter a single orphaned file or directory
-    --tmp DIR    -same as below
   purge FILE   -purge an object list, expects a gfo-sorted.txt type of list
     --tmp DIR    -an off-disk temporary directory to optimize the filter process
                   the directory will be created and deleted on completion
+  filter PATH  -filter a single orphaned file or directory, will not recurse a directory
+    --tmp DIR    -same as above
+  rmdir PATH   -recursively filter all items of a directory
+    --tmp DIR    -same as above
   help GIT-USERNAME CLONE-REPO
                -this menu, you can pass a username and clone-repo name into the params
                 be used in place of <username> and <clone-repo> below
@@ -261,13 +323,13 @@ COMMANDS
 EXAMPLES
 --------
   - build list file -> gfo-sorted.txt
-  $ ${REPO}> ~/git-filter-orphans find
+  $ $REPO> ~/git-filter-orphans find
 
   - confirm contents of the generated list
-  $ ${REPO}> cat gfo-sorted.txt
+  $ $REPO> cat gfo-sorted.txt
 
   - purge the list created in "gfo-sorted.txt":
-  $ ${REPO}> ~/git-filter-orphans purge gfo-sorted.txt
+  $ $REPO> ~/git-filter-orphans purge gfo-sorted.txt
 
 
 COMPLETE GUIDE - READ FIRST
@@ -276,34 +338,34 @@ This assumes you want to create a clone of your repo for liability
 purposes and have already created a new repo for this.
 
 #create the clone
-  $ > git clone --bare git@github.com:${GIT_USER}/${REPO} ${REPO}.git
+  $ > git clone --bare git@github.com:$GIT_USER/$REPO ${REPO}.git
   $ > cd ${REPO}.git
-  $ ${REPO}.git> git push --mirror git@github.com:${GIT_USER}/${CLONE_REPO}
+  $ ${REPO}.git> git push --mirror git@github.com:$GIT_USER/$CLONE_REPO
 
 #clone the new remote repo
-  $ ${REPO}.git> cd .. && git clone git@github.com:${GIT_USER}/${CLONE_REPO} && cd "${CLONE_REPO}"
+  $ ${REPO}.git> cd .. && git clone git@github.com:$GIT_USER/$CLONE_REPO && cd "$CLONE_REPO"
 
-#create a ${SORT_FILE} file of orphaned objects and their size in bytes
-  $ ${CLONE_REPO}> ~/git-filter-orphans find
+#create a $SORT_FILE file of orphaned objects and their size in bytes
+  $ $CLONE_REPO> ~/git-filter-orphans find
 
-#the ${SORT_FILE} looks good
+#the $SORT_FILE looks good
 #lets delete the items in it with git-filter-branch
-  $ ${CLONE_REPO}> ~/git-filter-orphans purge ${SORT_FILE}
+  $ $CLONE_REPO> ~/git-filter-orphans purge $SORT_FILE
 
 #for this next step we need to clean our old references
 #the easiest way is to just clone the repo locally and copy your backup git config
-  $ ${CLONE_REPO}> ~/git-filter-orphan clone
+  $ $CLONE_REPO> ~/git-filter-orphan clone
 	
 #or run the manual GC actions needed to clear the repo of it's history, but be careful,
 #the git commands ran here can be volatile, might want to make a backup
 #see: http://git-scm.com/docs/git-filter-branch#_checklist_for_shrinking_a_repository
-  $ ${CLONE_REPO}> ~/git-filter-orphans gc
+  $ $CLONE_REPO> ~/git-filter-orphans gc
 
 #now we have a clean repo ready to be pushed
-  $ ${CLONE_REPO}> ~/git-filter-orphans update
+  $ $CLONE_REPO> ~/git-filter-orphans update
 
 EOL
-	if [ "${CLONE_REPO}" == "${REPO}" ]; then
+	if [ "$CLONE_REPO" == "$REPO" ]; then
 		echo "---"
 		echo "Warning: Your target cloned repo is the same as your current!"		
 		echo "---"
